UPDATE merchants SET menu = '[
    {"item": "Chicharrón bbq", "price": 17000, "prep_min": 15, "available": true},
    {"item": "Chicharrón", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Pollo apanado", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Mojarra", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Basa", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Carne desmechada", "price": 14000, "prep_min": 10, "available": true},
    {"item": "Pollo desmechado", "price": 12000, "prep_min": 10, "available": true},
    {"item": "Carne molida", "price": 14000, "prep_min": 10, "available": true},
    {"item": "Pollo guisado", "price": 12000, "prep_min": 15, "available": true},
    {"item": "Carne guisada", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Cerdo guisado", "price": 12000, "prep_min": 15, "available": true},
    {"item": "Chivo guisado", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Panza", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Albondiga", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Gallina guisada", "price": 20000, "prep_min": 15, "available": true},
    {"item": "Hígado en bistec", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Carne en bistec", "price": 14000, "prep_min": 15, "available": true},
    {"item": "Salteado", "price": 16000, "prep_min": 15, "available": true},
    {"item": "Lomo de cerdo asado", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Pechuga asada", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Chuleta asada", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Res asada", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Pechuga gratinada", "price": 17000, "prep_min": 20, "available": true},
    {"item": "Asado tradicional (papa/patacón, ensalada, proteína)", "price": 20000, "prep_min": 20, "available": true}
]'::jsonb WHERE name = 'Sr. Loquillo''s';

UPDATE merchants SET menu = '[
    {"item": "Gallina guisada", "price": 20000, "prep_min": 15, "available": true},
    {"item": "Chivo en coco", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Panza en coco", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Lomo salteado", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Carne molida", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Carne en bistec", "price": 15000, "prep_min": 15, "available": true},
    {"item": "Lomo gratinado", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Pechuga gratinada", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Chicharrones BBQ", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Lomo BBQ", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Pechuga BBQ", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Lomo asado", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Pechuga asada", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Chicharrones fritos", "price": 20000, "prep_min": 15, "available": true},
    {"item": "Mojarra frita", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Bocachico frito", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Sopa pequeña", "price": 6000, "prep_min": 5, "available": true},
    {"item": "Sopa grande", "price": 12000, "prep_min": 5, "available": true},
    {"item": "Pastel Masa cerdo", "price": 12000, "prep_min": 5, "available": true},
    {"item": "Pastel Masa pollo", "price": 12000, "prep_min": 5, "available": true},
    {"item": "Pastel Arroz cerdo", "price": 12000, "prep_min": 5, "available": true}
]'::jsonb WHERE name = 'Restaurante Donde Isne';

UPDATE merchants SET menu = '[
    {"item": "Cerdo guisado (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Chivo en coco (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Panza en coco (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Costilla guisada (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Muchacho guisado (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Pollo en coco (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Carne en bistec (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Carne desmechada (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Sobrebarriga guisada (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Carne molida (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Albondigas (Corriente)", "price": 13000, "prep_min": 15, "available": true},
    {"item": "Carne asada", "price": 17000, "prep_min": 20, "available": true},
    {"item": "Pechuga asada", "price": 17000, "prep_min": 20, "available": true},
    {"item": "Lomo de cerdo asado", "price": 17000, "prep_min": 20, "available": true},
    {"item": "Sobrebarriga asada", "price": 16000, "prep_min": 20, "available": true},
    {"item": "Pechuga gratinada", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Lomo gratinado", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Menu Especial - Chicharrón", "price": 20000, "prep_min": 20, "available": true},
    {"item": "Menu Especial - Gallina guisada", "price": 18000, "prep_min": 20, "available": true},
    {"item": "Menu Especial - Bocachico frito", "price": 25000, "prep_min": 20, "available": true},
    {"item": "Menu Especial - Lengua en coco", "price": 15000, "prep_min": 20, "available": true}
]'::jsonb WHERE name = 'Restaurante Maye';
